#!/bin/bash -e

GITHUB_USERNAME="$1"

if [ -z "$GITHUB_USERNAME" ]; then
  read -p "Enter Github username: " GITHUB_USERNAME
fi

if [ -z "$GITHUB_TOKEN" ]; then
  read -sp "Enter Github access token: " GITHUB_TOKEN
fi

# Set up variables for pagination
PAGE=1
PER_PAGE=100
HAS_NEXT_PAGE=true

# Loop through pages of repositories
while [ "${HAS_NEXT_PAGE}" == true ]
do
  API_URL="https://api.github.com/users/$GITHUB_USERNAME/repos?page=$PAGE&per_page=$PER_PAGE"
  REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $API_URL)

  if [ ${#REPOS} -lt 10 ]; then
    HAS_NEXT_PAGE=false
  else
    echo $REPOS | jq -rc '.[]' |\
    while read repo_data
    do
      repo_name=$(echo $repo_data | jq -r '.name')

      # Thanks Copilot
      if [ -d "$repo_name" ]; then
        echo "Skipping $repo_name because it already exists."
        continue
      fi

      repo_url=$(echo $repo_data | jq -r '.ssh_url')
      git clone "$repo_url"
    done

    # Move on to the next page of repositories
    PAGE=$((PAGE+1))
  fi
done

# Done!
echo "All repositories have been cloned."
