#!/usr/bin/env bash

COMMAND="$1"
HOOK="$HOME/.dotfiles-git/hooks/post-commit"

if [ ! -f "$HOOK" ]; then
  if [ ! -f "$HOOK.bak" ]; then
    echo "No hook found."
    exit 1
  fi
fi

case "$COMMAND" in

  enable)
    mv "$HOOK.bak" "$HOOK";;

  disable)
    mv "$HOOK" "$HOOK.bak";;

  *)
    echo "Valid arguments:"
    echo "  - enable"
    echo "  - disable"
    exit 1

esac
