#!/usr/bin/env bash

DOT="git --git-dir=$HOME/.dotfiles-git/ --work-tree=$HOME"

function gitignore() {
  $HOME/bin/helpers/read-gitignore.sh "$1" $HOME/.dotinclude
}

ERRORS=$($DOT pull 2>&1)

if [ $? -ne 0 ]; then
    echo 'Error running git pull:'
    echo $ERRORS
    exit 1
fi

dothook disable

savegame --no-push kerbal
savegame --no-push minecraft
savegame --no-push rimworld
savegame --no-push the-cave

# Include paths in .dotinclude
while read path; do
  $DOT add "$path"
done < <(gitignore include)

# Exclude paths with ! in .dotinclude
while read path; do
  if [ -d "$path" ] || [ -f "$path" ]; then
    $DOT reset "$path"
  fi
done < <(gitignore exclude)

$DOT commit -am "Sync $(date +%d-%m-%Y) ($USER)"
$DOT push

dothook enable
