#!/usr/bin/env bash

DOT=$($HOME/bin/helpers/dot.sh)

function gitignore() {
  $HOME/bin/helpers/read-gitignore.sh "$1" $HOME/.dotinclude
}

ERRORS=$($DOT pull 2>&1)

if [ $? -ne 0 ]; then
    echo 'Error running git pull:'
    echo $ERRORS
    exit 1
fi

$HOME/bin/dothook disable

$HOME/bin/savegame --no-push kerbal
$HOME/bin/savegame --no-push minecraft
$HOME/bin/savegame --no-push rimworld
$HOME/bin/savegame --no-push the-cave

# Include paths in .dotinclude
while read path; do
  $DOT add "$path"
done < <(gitignore include)

# Exclude paths with ! in .dotinclude
while read path; do
  if [ -d "$path" ] || [ -f "$path" ]; then
    $DOT reset "$path"
  fi
done < <(gitignore exclude)

$DOT commit -am "Sync $(date +%d-%m-%Y) ($USER)" > /dev/null
$DOT push

$HOME/bin/dothook enable
