#!/bin/bash

dir=$(pwd)

until [ -f "$dir/build" ] || [ "$dir" = "/" ]
do
	dir=$(dirname $dir)
done


if [ ! -f "$dir/build" ]
then
	echo "Not on a build system"
	exit
fi

echo -e "Running '$dir/build'...\n"
bash $dir/build $@
echo -e "\nDone"
