#!/bin/bash -e

BRANCH="$1"
[ -z "$BRANCH" ] && BRANCH="$(git branch --show-current)"

git fetch

if [ -z "$BRANCH" ]; then
	echo "No branch specified and no current branch detected. Exiting."
	exit 1
fi

git rebase origin/$BRANCH
