#!/bin/bash

gource \
  -s .03 \
  -1280x720 \
  --auto-skip-seconds .1 \
  --multi-sampling \
  --stop-at-end \
  --disable-progress \
  --user-scale 2 \
  --highlight-users \
  --date-format "%Y/%m/%d" \
  --hide mouse,filenames \
  --file-idle-time 0 \
  --max-files 0  \
  --background-colour 000000 \
  --font-size 25 \
  --output-ppm-stream - \
  | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4
  # --key \
  # --output-framerate 30 \
