#!/bin/bash -e
failed=

function main() {
  if [ "$#" -eq 0 ]; then
    help
    return 1
  fi

  pushd "$(find_git_directory)" >/dev/null
    DIR="./" run_in "$@"
  popd >/dev/null

  [ -n "$failed" ] && exit 1
}

function run_in() {
  if [ -f .gitmodules ]; then
    list_submodules | while read path; do
      pushd $path >/dev/null
        DIR="$DIR$path/" run_in "$@"
      popd >/dev/null
    done
  fi

  echo -e "🌲 \033[0;32mRunning in $DIR\033[0;0m" >&2
  if ! git "$@"; then
    echo -e "🌲 \033[0;31m < Failed to run  command in $DIR\033[0;0m" >&2
    failed=1
  fi
}

function list_submodules() {
  cat .gitmodules | grep 'path =' | sed 's/path = //'
}

function find_git_directory() {
  current_dir=$(pwd)

  while [ "$current_dir" != "/" ]; do
    if [ -d "$current_dir/.git" ]; then
      echo "$current_dir"
      return 0
    fi

    current_dir=$(dirname "$current_dir")
  done

  # No .git directory is found
  return 1
}

function help() {
  echo "Run a git command in the root repository and all submodules."
  echo "Usage: $0 <git-command>"
  return 1
}

# --- ENTRY POINT ---

main "$@"
