#!/bin/bash -e

prefix=
a_set=
b=
a=

function main() {
  git fetch
  ensure-branch-exists "$b"
  ensure-branch-exists "$a"
  common_hash="$(git merge-base "$a" "$b")"
  print-common-ancestor "$common_hash"
  echo
  echo ---
  echo
  print-changes-since "$common_hash" "$a" "$b"
  echo
  echo ---
  echo
  print-changes-since "$common_hash" "$b" "$a"
}

function ensure-branch-exists() {
  git rev-parse --verify "$1" >/dev/null 2>&1 && return

  if git rev-parse --verify "origin/$1" >/dev/null 2>&1; then
    git branch --track "$1" "origin/$1"
    return
  fi

  echo "Branch not found: $1" >&2
  exit 5
}

function print-common-ancestor() {
  local common_hash="$1"
  echo -e "Comparing \033[0;32m$a\033[0m and \033[0;33m$b\033[0m from common ancestor:"
  echo
  git log --oneline -n1 "$common_hash"
}

function print-changes-since() {
  local commit="$1"
  local branch="$2"
  local other_branch="$3"

  if [[ "$(git rev-parse "$branch")" == "$commit" ]]; then
    echo -e "✅ \033[0;32m$other_branch\033[0m has all commits in \033[0;33m$branch\033[0m"
    return
  fi

  echo -e "Commits in \033[0;33m$branch\033[0m not in \033[0;32m$other_branch\033[0m since $commit:"
  echo
  git log --oneline "$commit".."$branch"
}

function usage() {
  echo "Usage: $(basename $0) [--origin] <branch-a> <branch-b>"
  echo
  echo "Options:"
  echo "  -h, --help        Show this help message and exit"
  echo "  -o, --origin      Compare against the remote tracking branches (e.g. origin/branch)"
}

function process-args() {
  local positional=()

  while [[ -n "$1" ]]; do
    case "$1" in
      -h|--help) usage; exit 0;;
      -o|--origin) prefix='origin/';;
      -*)
        echo "Unknown option: $1" >&2
        exit 1;;
      *)
        positional+=("$1")
        # if [[ -z "$b" ]]; then
        #   b="$1"
        # elif [[ -z "$a_set" ]]; then
        #   a="$b"
        #   b="$1"
        #   a_set=1
        # else
        #   echo "Too many arguments: $b $a $1" >&2
        #   exit 2
        # fi
        ;;
    esac
    shift
  done

  case "${#positional[@]}" in
    0) a="$(get-current-ref)";;
    1) a="$(get-current-ref)"; b="${positional[0]}";;
    2) a="${positional[0]}"; b="${positional[1]}";;
    *)
      echo "Too many arguments: ${#positional[@]}" >&2
      usage >&2
      exit 2;;
  esac

  if [[ -n "$prefix" ]]; then
    # git fetch
    if [[ -z "$b" ]]; then
      b="$prefix$a"
    else
      a="$prefix$a"
      b="$prefix$b"
    fi
  fi

  if [[ -z "$a" || -z "$b" ]]; then
    usage >&2
    exit 3
  fi

  if [[ "$a" == "$b" ]]; then
    echo "Both branches are the same: $a" >&2
    exit 4
  fi
}

function get-current-ref() {
  local result="$(git branch --show-current 2>/dev/null)"
  [[ -z "$result" ]] && result="$(git name-rev --name-only HEAD 2>/dev/null)"
  echo "$result"
}

# --- ENTRY POINT ---
process-args "$@"
main