#!/bin/bash -e

FROM="$1"
TO="$2"

if [ -z "$FROM" ] || [ -z "$TO" ]
then
  echo "Usage $0 <from_branch> <to_branch>"
  exit 1
fi

git checkout "$FROM"
git pull origin "$FROM"
git checkout "$TO"
git pull origin "$TO"

git merge "$FROM"

if [ "$3" == "push" ]
then
  git push origin "$TO"
fi