#!/bin/bash

NAME="mssql"
ID=$(docker ps -aq -f "name=$NAME")

if [ -z "$ID" ]
then
    docker run \
        --name "$NAME" \
        -e 'ACCEPT_EULA=Y' \
        -e 'SA_PASSWORD=mssqlStrongestPassword1' \
        -p 1433:1433 \
        -d \
        mcr.microsoft.com/mssql/server:2017-latest
else
    docker start mssql
fi
