#!/bin/sh

if [ $# -ne 3 ]
then
	echo "Usage: rename-files <file-extension> <search-for> <replace-by>"
	exit
fi

extension="$1"
search="$2"
replace="$3"

find -name "*.$extension" -exec sed -i "s/$search/$replace/g" {} \;
