#!/usr/bin/env bash

GAME="$1"
PUSH=true

if [ "$GAME" = "--no-push" ]; then
  PUSH=false
  GAME="$2"
fi

case "$GAME" in

  kerbal)
    $DOT add "$HOME/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/saves/por defecto";;

  minecraft)
    $DOT add "$HOME/Library/Application Support/minecraft/saves/";;

  rimworld)
    $DOT add "$HOME/Library/Application Support/RimWorld/Saves/";;

  the-cave)
    $DOT add "$HOME/Library/Application Support/Doublefine/TheCave/76561198058830888/";;

  *)
    echo "Valid arguments:"
    echo "  - kerbal"
    echo "  - minecraft"
    echo "  - rimworld"
    echo "  - the-cave"
    exit 1

esac

$DOT commit -m "Savegame: $GAME" > /dev/null

if [ "$PUSH" = true ]; then
  $DOT push
fi
