#!//bin/sh -e

source="/Users/amatiasq/Downloads"
destination="/Volumes/home"
file="$source/$1"

if [ ! -f "$file" ]; then
  if [ ! -d "Takeout" ]; then
    echo "File not found: $file"
    exit 1
  else
    echo cp -r Takeout "$destination"
    cp -r Takeout "$destination"
    echo "Removing Takeout dir..."
    rm -r Takeout
    exit 0
  fi
fi

echo tar -xzf "$file"
tar -xzf "$file" > /dev/null
echo "Removing $file..."
rm "$file"

echo cp -r Takeout "$destination"
cp -r Takeout "$destination"
echo "Removing Takeout dir..."
rm -r Takeout
