#!/bin/bash -e

a=
b=
prefix=

function usage() {
  echo "Usage: $(basename $0) [--origin] [<branch-a> [<branch-b>]]"
  echo
  echo "Options:"
  echo "  -h, --help        Show this help message and exit"
  echo "  -o, --origin      Compare against the remote tracking branches"
  echo
  echo "Examples:"
  self="$(basename $0)"
  echo "  $self --origin                # Compare the current branch against its upstream"
  echo "  $self main                    # Compare the current branch against main"
  echo "  $self main --origin           # Compare the origin's current branch against origin/main"
  echo "  $self main feature            # Compare main against feature"
  echo "  $self --origin main feature   # Compare origin/main against origin/feature"
  echo
  echo "The order of parameters doesn't matter."
}

function main() {
  git fetch
  ensure-branch-exists "$a"
  ensure-branch-exists "$b"

  local common_hash="$(git merge-base "$a" "$b")"
  local a_print="\033[0;32m$a\033[0m"
  local b_print="\033[0;33m$b\033[0m"

  print-common-ancestor "$common_hash" "$a_print" "$b_print"
  echo
  echo ---
  echo
  print-changes-since "$common_hash" "$a" "$a_print" "$b_print"
  echo
  echo ---
  echo
  print-changes-since "$common_hash" "$b" "$b_print" "$a_print"
  echo
}

function ensure-branch-exists() {
  git rev-parse --verify "$1" >/dev/null 2>&1 && return

  if git rev-parse --verify "origin/$1" >/dev/null 2>&1; then
    git branch --track "$1" "origin/$1"
    return
  fi

  echo "Branch not found: $1" >&2
  exit 5
}

function print-common-ancestor() {
  echo -e "Comparing $2 and $3 from common ancestor:"
  echo
  git log --oneline -n1 "$1"
}

function print-changes-since() {
  local commit="$1"
  local branch="$2"
  local branch_print="$3"
  local other_branch="$4"

  if [[ "$(git rev-parse "$branch")" == "$commit" ]]; then
    echo -e "✅ $other_branch has all commits in $branch_print"
    return
  fi

  echo -e "Commits in $branch_print not in $other_branch:"
  echo
  git log --oneline "$commit".."$branch"
}

function process-args() {
  local positional=()

  while [[ -n "$1" ]]; do
    case "$1" in
      -h|--help) usage; exit 0;;
      -o|--origin) prefix='origin/';;
      -*)
        echo "Unknown option: $1" >&2
        exit 1;;
      *) positional+=("$1");;
    esac
    shift
  done

  case "${#positional[@]}" in
    0) a="$(get-current-ref)";;
    1) a="$(get-current-ref)"; b="${positional[0]}";;
    2) a="${positional[0]}"; b="${positional[1]}";;
    *)
      echo "Too many arguments: ${#positional[@]}" >&2
      usage >&2
      exit 2;;
  esac

  if [[ -n "$prefix" ]]; then
    # git fetch
    if [[ -z "$b" ]]; then
      b="$prefix$a"
    else
      a="$prefix$a"
      b="$prefix$b"
    fi
  fi

  if [[ -z "$a" || -z "$b" ]]; then
    usage >&2
    exit 3
  fi

  if [[ "$a" == "$b" ]]; then
    echo "Both branches are the same: $a" >&2
    exit 4
  fi
}

function get-current-ref() {
  local result="$(git branch --show-current 2>/dev/null)"
  [[ -z "$result" ]] && result="$(git name-rev --name-only HEAD 2>/dev/null)"
  echo "$result"
}

# --- ENTRY POINT ---
process-args "$@"
main
