#!/bin/bash

home="$1"


function internal() {
	original=$(pwd)
	cd "$1"
	prefix="$2"

	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")

	echo '    Creating dirs'
	for dir in $(find . -type d)
	do
		if [ ! -d "$prefix/$dir" ]
		then
			echo "Creating dir $prefix/$dir"
			mkdir "$prefix/$dir"
		fi
	done

	echo '    Copying files'
	for file in $(find . -type f)
	do
		echo "Copying $file to $prefix/$file"
		cp "$file" "$prefix/$file"
	done

	IFS=$SAVEIFS
	cd $original
}



echo 'Global configurations'
internal root /

echo 'User configurations'
internal home $home

echo 'Custom configurations'
cat custom/usr/share/vim/vim73/filetype.dart.vim >> /usr/share/vim/vim73/filetype.vim
