#!/bin/bash -e

if [ "`whoami`" != "root" ]
then
	echo "This script must be executed as root"
	exit
fi

log="/dev/null"

if [ "`arch`" == "x86_64" ]
then
	arch="amd64"
else
	arch="i386"
fi

cd /tmp



echo "Installing Google Chrome..."

echo "    Dependences"
apt-get -qq install -y libcurl3 libnspr4-0d libnss3-1d libxss1

echo "    Downloading"
wget -q -O chrome.$$.deb https://dl-ssl.google.com/linux/direct/google-chrome-stable_current_$arch.deb

echo "    Installing"
dpkg -i chrome.$$.deb >> $log



echo "Installing Skype..."
echo "    Dependences"
apt-get -qq install -y lib32stdc++6 lib32asound2 ia32-libs libc6-i386 libc6-i386 lib32gcc1

echo "    Downloading"
wget -q -O skype.$$.deb http://download.skype.com/linux/skype-ubuntu_2.2.0.35-1_$arch.deb

echo "    Installing"
dpkg -i skype.$$.deb >> $log


#echo "Installing Dropbox..."
#wget -O dropbox.$$.deb http://linux.dropbox.com/packages/nautilus-dropbox_0.6.7_$arch.deb 2> $log > $log
#dpkg -i dropbox.$$.deb > $log

echo "Done"
