#!/bin/bash

log="/dev/null"

for project in \
	"glib" \
	"promise" \
	"jsbase" \
	"pomo"
do
	echo "Found project $project"
	cd
	dir=~/repos/$project

	if [ ! -d "$dir" ]
	then
		echo "    Cloning into $dir"
		git clone "https://github.com/amatiasq/$project.git" "$dir" &> $log
		cd "$dir"
		git submodule update --init --recursive &> $log
	fi
done

for project in \
	"desktop" \
	"drive" \
	"draw"
do
	echo "Found project LORELEI::$project"
	cd
	dir=~/repos/$project

	if [ ! -d "$dir" ]
	then
		echo "    Cloning into $dir"
		git clone "https://github.com/lorelei-group/$project.git" "$dir" &> $log
		cd "$dir"
		git submodule update --init --recursive &> $log
	fi
done

echo "Done"
