#!/bin/bash

log="/dev/null"

for project in \
	"lorelei" \
	"BRIAP" \
	"Life" \
	"LifeJS" \
	"Selchi" \
	"Sassmine" \
	"jsbase" \
	"signature.js" \
	"bio"
do
	echo "Found project $project"
	cd
	dir=~/repos/$project

	if [ ! -d "$dir" ]
	then
		echo "    Cloning into $dir"
		git clone "git@github.com:amatiasq/$project.git" "$dir" &> $log
		cd "$dir"
		git submodule update --init --recursive &> $log
	fi
done

echo "Done"
