#!/bin/bash

# @raycast.schemaVersion 1
# @raycast.title Displays: Restore order for YEGO
# @raycast.mode silent

displayplacer "id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:1512x982 hz:120 color_depth:8 enabled:true scaling:on origin:(0,0) degree:0" "id:45AED1BC-6A64-4D02-98B9-0D74B91D5689 res:1920x1080 hz:60 color_depth:8 enabled:true scaling:off origin:(1512,0) degree:0" "id:11ADCC68-8318-484E-A29E-3759FD39925E res:2560x1440 hz:144 color_depth:8 enabled:true scaling:off origin:(872,-1440) degree:0" "id:1ABF9098-F53F-4DEB-9583-3AA4A1419873 res:1080x1920 hz:60 color_depth:8 enabled:true scaling:off origin:(3432,-840) degree:0"

afplay /System/Library/Sounds/Basso.aiff
